### ISSUE TITLE
chore: disable ARRAffinity cookie

### ISSUE THREAD

**Issue by jahorton** [keymanapp/api.keyman.com#142]
Recently saw this message in the developer console during testing:

```
A cookie associated with a cross-site resource at http://api.keyman.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

We'll probably need to make some adjustments corresponding to this.

**Comment by mcdurdin** [comment]
I no longer see this occurring. It would be helpful to have a repro for these kinds of issues -- e.g. a link to the site where this was happening.

**Comment by jahorton** [comment]
> a link to the site where this was happening.

I believe this was happening for in-repo pages under `web/testing`.  I'm not 100% whether it involved localhost mode or `file:///` mode.
