### ISSUE TITLE
bug: TC build fail notification not working on staging

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/api.keyman.com#203]
Per @mcdurdin , the TC notification of build fails isn't working for api.keyman-staging.com (It is fine for api.keyman.com)

Investigate [error](https://build.palaso.org/buildConfiguration/Keyboards_NotifyApiKeymanComOfUpdate/401837?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true).

Perhaps involving a batch file creating a script...

**Comment by darcywong00** [comment]
It looks like we need @tim-eves 's help in declaring a server variable in k8s (for api.keyman-staging.com)

**Comment by darcywong00** [comment]
Depends on #205

**Comment by mcdurdin** [comment]
TC notification is now working, but the script itself is not yet triggering the database rebuild, because we probably still don't have the replacement for the Azure webjob which did the rebuild in the background.
