### ISSUE TITLE
feat: Deploy staging site with Kubernetes 🦭

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/api.keyman.com#205]
@tim-eves - Would you be avaible sometime the week Aug 21-25 to help us deploying the staging branch to api.keyman-staging.com?

Similar to the work you did on keymanapp/help.keyman.com#616, keymanapp/help.keyman.com#641, keymanapp/help.keyman.com#676?

If not available, then maybe we schedule for later in September

**Comment by mcdurdin** [comment]
Notes here:

* Database needs to be persistent
* Consider strategy for database rebuild -- currently uses a webhook and does a background job rebuild to completely avoid downtime. Hot swaps between schemas in the database. Similar pattern probably needed.
* Consider strategy for deployment of site -- needs to hotswap to avoid downtime (something like 5 requests/second on the keyman sites so even short downtime is pretty impactful)

**Comment by darcywong00** [comment]
@tim-eves started this at EMDC and will continue working in the background.  

We 3 can discuss deployment before A17S24.
He proposed an alternative to the API hook with [Fleet](https://fleet.rancher.io/).

**Comment by darcywong00** [comment]
I think this is now handled as part of keymanapp/keyman.com#403 

> _control/webhook/deploy
>   *  webhook on github (staging)
>    * test

**Comment by mcdurdin** [comment]
This is complete
