### ISSUE TITLE
bug: Error 422 when submitting Keyman diagnostic.

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/api.keyman.com#214]
I was trying to submit a diagnostic report about a "stuck" shift issue.

I typed in my address, name and description, and sent.

Error 422, you must select a valid user.

![image](https://github.com/keymanapp/api.keyman.com/assets/986339/7bf2769e-fef1-4d84-bc76-98874d2fede0)

Edit: It made the most sense to send this here, though it could be an API or Keyman Developer bug,

**Comment by mcdurdin** [comment]
I've reproduced this here, looking into it now

**Comment by mcdurdin** [comment]
Tested, confirmed fixed:

![image](https://github.com/keymanapp/api.keyman.com/assets/4498365/3a29fa3d-0b79-4c16-94b6-d26f87a8f468)
