### ISSUE TITLE
[api.keyman.com] languages search not handling script tag?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/api.keyman.com#3]
The query https://keyman.com/keyboards?q=lana returns

## Keyboards matching 'lana'
[Boonkit Unicde](https://keyman.com/keyboards/sil_boonkit)

## Languages matching Lana: 
[Thai, Northern (Lanatai)](https://keyman.com/keyboards/languages/nod)

but following the languages link, it's not finding `nod` (The Boonkit keyboard is now under `nod-Lana`)

**Comment by mcdurdin** [comment]
Complete in staging.
