### ISSUE TITLE
Cloud API returns for KMW: find closest BCP-47 match

### ISSUE THREAD

**Issue by jahorton** [keymanapp/api.keyman.com#45]
In reference to https://github.com/keymanapp/keyman/issues/2785:

KeymanWeb's bookmarklet is currently experiencing issues with the API-returned keyboard stub.  On KMW 13.0.105, https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=13.0&keyboardid=sil_uganda_tanzania@ikx&timerid=3 returns:

```
keyman.register({"options":{"context":"keyboard","dateFormat":"standard","device":"any","keyboardBaseUri":"https://s.keyman.com/keyboard/","fontBaseUri":"https://s.keyman.com/font/deploy/","keyboardid":"sil_uganda_tanzania@ikx","keyboardVersion":"current"},"keyboard":[{"id":"sil_uganda_tanzania","name":"Uganda-Tanzania Bantu (SIL)","filename":"sil_uganda_tanzania/1.1.1/sil_uganda_tanzania-1.1.1.js","version":"1.1.1","source":"https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_uganda_tanzania","devices":{"phone":2,"tablet":2,"desktop":2},"languages":[]}],"timerid":"3"});
```

Note this tidbit at the very end: `"languages":[]`.  As `ikx` isn't _directly_ matching anything in the Cloud API's database, no languages are returned... which causes KMW to not register the keyboard.

**Comment by mcdurdin** [comment]
Fixes for #46 will stop this being an issue. I will close this issue because I don't want to change the underlying API.
