### ISSUE TITLE
package-version: Clarifying results for legacy keyboards

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/api.keyman.com#58]
I was investigating keymanapp/keyman#3134 to see if I could migrate legacy deprecated keyboards with the package-version endpoint. (e.g. replace `us` and `european2` keyboards with the latest `sil_euro_latin.kmp`)

The following queries return "kmp" links to a directory (kmp doesn't exist):
https://api.keyman.com/package-version?platform=android&keyboard=european2
```json
{
    "keyboards": {
        "european2": {
            "version": "1.6",
            "kmp": "https://downloads.keyman.com/keyboards/european2/1.6/"
        }
    }
}
```

https://api.keyman.com/package-version?platform=android&keyboard=us
```json
{
    "keyboards": {
        "us": {
            "version": "1.0",
            "kmp": "https://downloads.keyman.com/keyboards/us/1.0/"
        }
    }
}
```

A couple questions:
1. Should the endpoint return *"error": "not found"* or *"error": "not available for \<platform>"*?
2. Is it up to the apps to determine the kmp file isn't available?

**Comment by mcdurdin** [comment]
> * Should the endpoint return _"error": "not found"_ or _"error": "not available for <platform>"_?

This is a bug in the API, yes. It needs to check for existence of .kmp. Noted for resolution.

You of course do need to handle download errors as well -- if the kmp file fails to download due to network issue, etc...

**Comment by mcdurdin** [comment]
This also relates to #1713: deprecated keyboards should offer a migration to the replacement. However, this possibly should not be completely automatic -- user should be prompted.
