### ISSUE TITLE
[api.keyman.com] Deprecate languages[] array in keyboard_info spec

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/api.keyman.com#6]
In the current [keyboard_info spec](https://help.keyman.com/developer/cloud/keyboard_info/1.0/),
![image](https://user-images.githubusercontent.com/7358010/49912050-6284a600-febb-11e8-8915-e96e659c34f5.png)

The `languages` field can be an array or object.

For #183, the keyboard_info will need to include display names. In order to do this:

1. We should deprecate the option for languages to be an array
2. Update the **KeyboardLanguageInfo Object** spec in api.keyman.com to add the fields:

| Member            | Required? | Notes |
| ---------             | :----------: | ------- |
|displayName      |                   |            |
| languageName |                   |            |
| scriptName       |                   |            |
| regionName      |                  |             |

3. Update the spec on help.keyman.com
4. Also need kmcomp to migrate existing .keyboard_info files (convert arrays to objects) and generate the new fields if not provided

Examples:
(replacing `fr-ca` with an example not involving suppressed script)
```
"dnj-Latn-LR" : {
  "displayName" : "Dan (Latin, Liberia)",
  "languageName": "Dan",
  "scriptName": "Latin",
  "regionName": "Liberia" }
```

```
"und-fonipa" : {
  "displayName": "IPA",
  "languageName": "Undetermined" }
```

**Comment by mcdurdin** [comment]
The languages array is only ever used in the source keyboard_info now. Distributed keyboard_info on the website always uses the object form (the keyboard_info merge tool transforms it).
